In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# /content/drive/MyDrive/Hackathon/Chuldong/

In [3]:
import pandas as pd
import numpy as np
from tqdm import tqdm
from pprint import pprint

In [4]:
statn =  pd.read_csv('/content/drive/MyDrive/Hackathon/Chuldong/tnSubwayStatn.csv')
statn

,﻿지하철역ID,지하철호선ID,지하철역명,지하철영문명,이전지하철역ID,다음지하철역ID,우편번호,기본주소,상세주소,전화번호,...,환승주차장설치여부,자전거보관소설치여부,지하철역X좌표,지하철역Y좌표,토피스역ID,연계역번호,지하철역코드,지하철노선이미지상단X좌표,지하철노선이미지상단Y좌표,급행정차여부(0:미정차/1:상행정차/2:하행정차/3:양방향정차)
0,﻿1009000931,﻿1009,﻿삼전,﻿Samjeon,﻿1009000930,﻿1009000932,﻿05603,﻿서울 송파구 삼전동,﻿133-13,﻿,...,﻿,﻿,﻿207754.59092,﻿445000.75279,﻿,﻿931,﻿931,﻿1908,﻿1277,﻿0
1,﻿1009000932,﻿1009,﻿석촌고분,﻿Seokchon Gobun,﻿1009000931,﻿1009000933,﻿05603,﻿서울 송파구 삼전동,﻿133-13,﻿,...,﻿,﻿,﻿208546.69877,﻿444785.34871,﻿,﻿932,﻿932,﻿1981,﻿1244,﻿0
2,﻿1009000933,﻿1009,﻿석촌,﻿Seokchon(Hansol Hospital),﻿1009000932,﻿1009000934,﻿138170,﻿서울특별시 송파구 송파동,﻿19,﻿02-6311-8151,...,﻿,﻿,﻿209473.4,﻿445088.5,﻿291207,﻿933,﻿933,﻿2014,﻿1209,﻿0
3,﻿1009000934,﻿1009,﻿송파나루,﻿Songpanaru,﻿1009000933,﻿1009000935,﻿05620,﻿서울 송파구 송파동,﻿48-11,﻿,...,﻿,﻿,﻿209928.13163,﻿445680.01312,﻿,﻿934,﻿934,﻿2073,﻿1149,﻿0
4,﻿1009000935,﻿1009,﻿한성백제,﻿Hanseong Baekje,﻿1009000934,﻿1009000936,﻿05545,﻿서울 송파구 방이동,﻿45-4,﻿,...,﻿,﻿,﻿210265.51556,﻿446364.36553,﻿,﻿935,﻿935,﻿2121,﻿1101,﻿0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
754,﻿1008000827,﻿1008,﻿모란,﻿Moran Station,﻿1008000826,﻿1008000827,﻿462130,﻿경기도 성남시 중원구 성남동,﻿1575,﻿031-721-4600,...,﻿,﻿,﻿211505.0278,﻿437183.4257,﻿291298,﻿827,﻿17,﻿2186,﻿1537,﻿0
755,﻿1007000760,﻿1007,﻿산곡,﻿Sangok,﻿1007000759,﻿1007000760,﻿21313,﻿인천광역시 부평구 길주로 지하379,﻿,﻿,...,﻿,﻿,﻿37.518622,﻿126.728939,﻿,﻿760,﻿52,﻿,﻿,﻿0
756,﻿1007000761,﻿1007,﻿석남,﻿Seongnam,﻿1007000760,﻿1007000761,﻿22802,﻿인천광역시 서구 가석로 257,﻿,﻿,...,﻿,﻿,﻿37.506193,﻿126.676203,﻿,﻿761,﻿53,﻿,﻿,﻿0
757,﻿1069073139,﻿1069,﻿송도달빛축제공원,﻿Songdo Moonlight Festival Park,﻿1069073138,﻿1069073139,﻿406840,﻿인천광역시 연수구 인천타워대로 지하424,﻿,﻿032-451-3188,...,﻿,﻿,﻿,﻿,﻿,﻿I139,﻿5130,﻿,﻿,﻿0
758,﻿1006000648,﻿1006,﻿신내,﻿Sinnae,﻿1006000647,﻿1006000648,﻿131230,﻿서울특별시 중랑구 망우동,﻿320-2,﻿1544-7788,...,﻿,﻿,﻿209112.3,﻿457025.0,﻿,﻿648,﻿48,﻿1991,﻿608,﻿0

In [5]:
statn.columns = ['지하철역ID', '지하철호선ID', '지하철역명', '지하철영문명', '이전지하철역ID', '다음지하철역ID', '우편번호',
       '기본주소', '상세주소', '전화번호', '팩스번호', '플랫폼구분', '하차문구분', '내부횡단여부', '화장실내외부',
       '환승호선수', '운영기관', '장애인시설설치여부', '환승주차장설치여부', '자전거보관소설치여부', '지하철역X좌표',
       '지하철역Y좌표', '토피스역ID', '연계역번호', '지하철역코드', '지하철노선이미지상단X좌표',
       '지하철노선이미지상단Y좌표', '급행정차여부(0:미정차/1:상행정차/2:하행정차/3:양방향정차)']
statn

,지하철역ID,지하철호선ID,지하철역명,지하철영문명,이전지하철역ID,다음지하철역ID,우편번호,기본주소,상세주소,전화번호,...,환승주차장설치여부,자전거보관소설치여부,지하철역X좌표,지하철역Y좌표,토피스역ID,연계역번호,지하철역코드,지하철노선이미지상단X좌표,지하철노선이미지상단Y좌표,급행정차여부(0:미정차/1:상행정차/2:하행정차/3:양방향정차)
0,﻿1009000931,﻿1009,﻿삼전,﻿Samjeon,﻿1009000930,﻿1009000932,﻿05603,﻿서울 송파구 삼전동,﻿133-13,﻿,...,﻿,﻿,﻿207754.59092,﻿445000.75279,﻿,﻿931,﻿931,﻿1908,﻿1277,﻿0
1,﻿1009000932,﻿1009,﻿석촌고분,﻿Seokchon Gobun,﻿1009000931,﻿1009000933,﻿05603,﻿서울 송파구 삼전동,﻿133-13,﻿,...,﻿,﻿,﻿208546.69877,﻿444785.34871,﻿,﻿932,﻿932,﻿1981,﻿1244,﻿0
2,﻿1009000933,﻿1009,﻿석촌,﻿Seokchon(Hansol Hospital),﻿1009000932,﻿1009000934,﻿138170,﻿서울특별시 송파구 송파동,﻿19,﻿02-6311-8151,...,﻿,﻿,﻿209473.4,﻿445088.5,﻿291207,﻿933,﻿933,﻿2014,﻿1209,﻿0
3,﻿1009000934,﻿1009,﻿송파나루,﻿Songpanaru,﻿1009000933,﻿1009000935,﻿05620,﻿서울 송파구 송파동,﻿48-11,﻿,...,﻿,﻿,﻿209928.13163,﻿445680.01312,﻿,﻿934,﻿934,﻿2073,﻿1149,﻿0
4,﻿1009000935,﻿1009,﻿한성백제,﻿Hanseong Baekje,﻿1009000934,﻿1009000936,﻿05545,﻿서울 송파구 방이동,﻿45-4,﻿,...,﻿,﻿,﻿210265.51556,﻿446364.36553,﻿,﻿935,﻿935,﻿2121,﻿1101,﻿0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
754,﻿1008000827,﻿1008,﻿모란,﻿Moran Station,﻿1008000826,﻿1008000827,﻿462130,﻿경기도 성남시 중원구 성남동,﻿1575,﻿031-721-4600,...,﻿,﻿,﻿211505.0278,﻿437183.4257,﻿291298,﻿827,﻿17,﻿2186,﻿1537,﻿0
755,﻿1007000760,﻿1007,﻿산곡,﻿Sangok,﻿1007000759,﻿1007000760,﻿21313,﻿인천광역시 부평구 길주로 지하379,﻿,﻿,...,﻿,﻿,﻿37.518622,﻿126.728939,﻿,﻿760,﻿52,﻿,﻿,﻿0
756,﻿1007000761,﻿1007,﻿석남,﻿Seongnam,﻿1007000760,﻿1007000761,﻿22802,﻿인천광역시 서구 가석로 257,﻿,﻿,...,﻿,﻿,﻿37.506193,﻿126.676203,﻿,﻿761,﻿53,﻿,﻿,﻿0
757,﻿1069073139,﻿1069,﻿송도달빛축제공원,﻿Songdo Moonlight Festival Park,﻿1069073138,﻿1069073139,﻿406840,﻿인천광역시 연수구 인천타워대로 지하424,﻿,﻿032-451-3188,...,﻿,﻿,﻿,﻿,﻿,﻿I139,﻿5130,﻿,﻿,﻿0
758,﻿1006000648,﻿1006,﻿신내,﻿Sinnae,﻿1006000647,﻿1006000648,﻿131230,﻿서울특별시 중랑구 망우동,﻿320-2,﻿1544-7788,...,﻿,﻿,﻿209112.3,﻿457025.0,﻿,﻿648,﻿48,﻿1991,﻿608,﻿0

In [6]:
def get_statn(statn):
    a = statn['지하철역ID'].to_list()
    b = statn['이전지하철역ID'].to_list()
    c = statn['다음지하철역ID'].to_list()
    d = statn['지하철호선ID'].to_list()
    e = statn['지하철역명'].to_list()
    for i in range(len(a)):
        a[i] = a[i].replace("\uFEFF", "")
        b[i] = b[i].replace("\uFEFF", "")
        c[i] = c[i].replace("\uFEFF", "")
        d[i] = d[i].replace("\uFEFF", "")
        e[i] = e[i].replace("\uFEFF", "")

    statn['지하철역ID'] = a    
    statn['이전지하철역ID'] = b
    statn['다음지하철역ID'] = c
    statn['지하철호선ID'] = d
    statn['지하철역명'] = e

    return statn

statn = get_statn(statn)

In [7]:
statn = statn.loc[:,['지하철역ID','지하철호선ID','지하철역명','이전지하철역ID','다음지하철역ID']]
statn

         지하철역ID 지하철호선ID     지하철역명    이전지하철역ID    다음지하철역ID
0    1009000931    1009        삼전  1009000930  1009000932
1    1009000932    1009      석촌고분  1009000931  1009000933
2    1009000933    1009        석촌  1009000932  1009000934
3    1009000934    1009      송파나루  1009000933  1009000935
4    1009000935    1009      한성백제  1009000934  1009000936
..          ...     ...       ...         ...         ...
754  1008000827    1008        모란  1008000826  1008000827
755  1007000760    1007        산곡  1007000759  1007000760
756  1007000761    1007        석남  1007000760  1007000761
757  1069073139    1069  송도달빛축제공원  1069073138  1069073139
758  1006000648    1006        신내  1006000647  1006000648

[759 rows x 5 columns]

In [8]:
statn_dict = {}
for index, row in statn.iterrows():
    statn_dict[row['지하철역ID']] = row['지하철역명'] 
statn_dict['1001080141'] = '광명'
statn_dict

{'1009000931': '삼전',
 '1009000932': '석촌고분',
 '1009000933': '석촌',
 '1009000934': '송파나루',
 '1009000935': '한성백제',
 '1009000936': '올림픽공원',
 '1009000938': '중앙보훈병원',
 '1078330016': '가재울',
 '1092004710': '정릉',
 '1078330019': '시민공원',
 '1078330020': '석바위시장',
 '1078330021': '인천시청',
 '1078330022': '석천사거리',
 '1078330023': '모래내시장',
 '1078330024': '만수',
 '1078330025': '남동구청',
 '1078330026': '인천대공원',
 '1067080129': '천마산',
 '1067080130': '마석',
 '1067080131': '대성리',
 '1067080132': '청평',
 '1067080133': '상천',
 '1067080134': '가평',
 '1067080135': '굴봉산',
 '1067080136': '백양리',
 '1067080137': '강촌',
 '1067080138': '김유정',
 '1067080139': '남춘천',
 '1067080140': '춘천',
 '1069073110': '계양',
 '1069073111': '귤현',
 '1069073112': '박촌',
 '1069073113': '임학',
 '1069073114': '계산',
 '1003000309': '원흥',
 '1063075319': '강매',
 '1065006501': '서울',
 '1065006502': '공덕',
 '1065006503': '홍대입구',
 '1065006504': '디지털미디어시티',
 '1065006505': '김포공항',
 '1065006506': '계양',
 '1065006507': '검암',
 '1065065071': '청라국제도시',
 '1065006509': '공항화물청사',
 '1065006510': '인천공항1터미널',
 '1065006511': '인천공항2터미널',
 '1071075250': '오이도',
 '1071075251': '달월',
 '1071075252': '월곶',
 '1063075331': '금촌',
 '1063075330': '금릉',
 '1063075329': '운정',
 '1063075327': '탄현',
 '1063075326': '일산',
 '1063075325': '풍산',
 '1063075324': '백마',
 '1063075323': '곡산',
 '1063075322': '대곡',
 '1063075321': '능곡',
 '1063075320': '행신',
 '1063075318': '화전',
 '1063075317': '수색',
 '1063075316': '디지털미디어시티',
 '1063075315': '가좌',
 '1063075314': '홍대입구',
 '1063075313': '서강대',
 '1063075312': '공덕',
 '1063075110': '용산',
 '1063075111': '이촌',
 '1063075335': '문산',
 '1063075334': '파주',
 '1063075333': '월롱',
 '1063075112': '서빙고',
 '1063075113': '한남',
 '1063075114': '옥수',
 '1063075115': '응봉',
 '1063075116': '왕십리',
 '1063075117': '청량리',
 '1063075118': '회기',
 '1063075119': '중랑',
 '1063075120': '상봉',
 '1063075121': '망우',
 '1063075122': '양원',
 '1063075123': '구리',
 '1063075124': '도농',
 '1063075125': '양정',
 '1063075126': '덕소',
 '1063075127': '도심',
 '1063075128': '팔당',
 '1063075129': '운길산',
 '1063075130': '양수',
 '1063075131': '신원',
 '1063075132': '국수',
 '1063075133': '아신',
 '1063075134': '오빈',
 '1063075135': '양평(경의중앙선)',
 '1063075136': '원덕',
 '1063075137': '용문',
 '1063080312': '신촌(경의중앙선)',
 '1063080313': '서울',
 '1067080119': '광운대',
 '1067080120': '상봉',
 '1067080121': '망우',
 '1067080122': '신내',
 '1067080123': '갈매',
 '1067080124': '별내',
 '1091004800': '인천공항1터미널',
 '1092004703': '4.19 민주묘지',
 '1092004704': '가오리',
 '1092004712': '보문',
 '1092004709': '북한산보국문',
 '1092004701': '북한산우이',
 '1092004706': '삼양',
 '1092004707': '삼양사거리',
 '1092004711': '성신여대입구',
 '1092004702': '솔밭공원',
 '1092004708': '솔샘',
 '1092004713': '신설동',
 '1067080125': '퇴계원',
 '1067080126': '사릉',
 '1067080127': '금곡',
 '1067080128': '평내호평',
 '1069073136': '인천대입구',
 '1069073137': '센트럴파크',
 '1069073138': '국제업무지구',
 '1071075253': '소래포구',
 '1071075254': '인천논현',
 '1071075255': '호구포',
 '1071075256': '남동인더스파크',
 '1071075257': '원인재',
 '1071075258': '연수',
 '1071075259': '송도',
 '1075075209': '청량리',
 '1075075210': '왕십리',
 '1075075211': '서울숲',
 '1075075212': '압구정로데오',
 '1075075213': '강남구청',
 '1075075214': '선정릉',
 '1075075215': '선릉',
 '1075075216': '한티',
 '1075075217': '도곡',
 '1075075218': '구룡',
 '1075075219': '개포동',
 '1075075220': '대모산입구',
 '1075075221': '수서',
 '1075075222': '복정',
 '1075075223': '가천대',
 '1075075224': '태평',
 '1075075225': '모란',
 '1075075226': '야탑',
 '1075075227': '이매',
 '1075075228': '서현',
 '1075075229': '수내',
 '1063075826': '효창공원앞',
 '1069073115': '경인교대입구',
 '1069073116': '작전',
 '1069073117': '갈산',
 '1069073118': '부평구청',
 '1069073119': '부평시장',
 '1069073120': '부평',
 '1069073121': '동수',
 '1069073122': '부평삼거리',
 '1069073123': '간석오거리',
 '1069073124': '인천시청',
 '1069073125': '예술회관',
 '1069073126': '인천터미널',
 '1069073127': '문학경기장',
 '1069073128': '선학',
 '1069073129': '신연수',
 '1069073130': '원인재',
 '1069073131': '동춘',
 '1069073132': '동막',
 '1069073133': '캠퍼스타운',
 '1069073134': '테크노파크',
 '1069073135': '지식정보단지',
 '1075075230': '정자',
 '1075075231': '미금',
 '1075075232': '오리',
 '1075075233': '죽전',
 '1075075234': '보정',
 '1075075235': '구성',
 '1077000687': '강남',
 '1092004705': '화계',
 '1078330003': '검단사거리',
 '1091004801': '장기주차장',
 '1091004802': '합동청사',
 '1091004803': '파라다이스 시티',
 '1091004804': '워터파크',
 '1091004805': '용유',
 '1065006508': '운서',
 '1093004001': '소사',
 '1093004002': '소새울',
 '1093004003': '시흥대야',
 '1093004004': '신천',
 '1093004005': '신현',
 '1093004006': '시흥시청',
 '1093004007': '시흥능곡',
 '1093004008': '달미',
 '1093004009': '선부',
 '1093004010': '초지',
 '1093004011': '원곡',
 '1093004012': '원시',
 '1077006813': '미금',
 '1065065042': '마곡나루',
 '1001080144': '금천구청',
 '1001080145': '석수',
 '1001080146': '관악',
 '1001080147': '안양',
 '1001080148': '명학',
 '1001080149': '금정',
 '1001080150': '군포',
 '1001080151': '당정',
 '1001080152': '의왕',
 '1001080153': '성균관대',
 '1001080154': '화서',
 '1001080155': '수원',
 '1001080156': '세류',
 '1001080157': '병점',
 '1001080158': '세마',
 '1001080159': '오산대',
 '1001080160': '오산',
 '1001080161': '진위',
 '1001080162': '송탄',
 '1001080163': '서정리',
 '1001080164': '지제',
 '1001080165': '평택',
 '1001080166': '성환',
 '1001080167': '직산',
 '1001080168': '두정',
 '1001080169': '천안',
 '1001080170': '봉명',
 '1001080171': '쌍용(나사렛대)',
 '1001080172': '아산',
 '1001080174': '배방',
 '1001080175': '온양온천',
 '1001080176': '신창',
 '1001801571': '서동탄',
 '1002000233': '대림',
 '1007000709': '장암',
 '1003000323': '녹번',
 '1007000725': '군자',
 '1007000726': '어린이대공원',
 '1007000727': '건대입구',
 '1007000728': '뚝섬유원지',
 '1007000729': '청담',
 '1003000324': '홍제',
 '1003000325': '무악재',
 '1003000326': '독립문',
 '1003000327': '경복궁',
 '1003000328': '안국',
 '1003000329': '종로3가',
 '1003000330': '을지로3가',
 '1003000331': '충무로',
 '1003000332': '동대입구',
 '1003000333': '약수',
 '1003000334': '금호',
 '1003000335': '옥수',
 '1003000336': '압구정',
 '1003000337': '신사',
 '1003000338': '잠원',
 '1003000339': '고속터미널',
 '1003000340': '교대',
 '1003000341': '남부터미널',
 '1003000342': '양재',
 '1003000343': '매봉',
 '1003000344': '도곡',
 '1003000345': '대치',
 '1003000346': '학여울',
 '1003000347': '대청',
 '1003000348': '일원',
 '1003000349': '수서',
 '1003000350': '가락시장',
 '1003000351': '경찰병원',
 '1003000352': '오금',
 '1004000409': '당고개',
 '1004000410': '상계',
 '1007000737': '남성',
 '1007000738': '숭실대입구',
 '1007000739': '상도',
 '1007000740': '장승배기',
 '1007000741': '신대방삼거리',
 '1007000742': '보라매',
 '1007000743': '신풍',
 '1007000744': '대림',
 '1007000745': '남구로',
 '1007000746': '가산디지털단지',
 '1007000747': '철산',
 '1007000748': '광명사거리',
 '1007000749': '천왕',
 '1007000750': '온수',
 '1007000751': '까치울',
 '1007000752': '부천종합운동장',
 '1007000753': '춘의',
 '1007000754': '신중동',
 '1007000755': '부천시청',
 '1007000756': '상동',
 '1007000757': '삼산체육관',
 '1007000758': '굴포천',
 '1007000759': '부평구청',
 '1008000812': '강동구청',
 '1008000813': '몽촌토성',
 '1008000814': '잠실',
 '1008000815': '석촌',
 '1008000816': '송파',
 '1008000817': '가락시장',
 '1008000818': '문정',
 '1008000819': '장지',
 '1006000646': '화랑대',
 '1004000447': '반월',
 '1004000448': '상록수',
 '1004000449': '한대앞',
 '1004000450': '중앙',
 '1004000451': '고잔',
 '1004000452': '초지',
 '1004000453': '안산',
 '1004000454': '신길온천',
 '1004000455': '정왕',
 '1004000456': '오이도',
 '1005000510': '방화',
 '1005000511': '개화산',
 '1005000512': '김포공항',
 '1005000513': '송정',
 '1005000514': '마곡',
 '1005000515': '발산',
 '1005000516': '우장산',
 '1005000517': '화곡',
 '1005000518': '까치산',
 '1005000519': '신정',
 '1005000520': '목동',
 '1005000521': '오목교',
 '1005000522': '양평',
 '1005000523': '영등포구청',
 '1005000524': '영등포시장',
 '1005000525': '신길',
 '1005000526': '여의도',
 '1005000527': '여의나루',
 '1005000528': '마포',
 '1005000529': '공덕',
 '1005000530': '애오개',
 '1005000531': '충정로',
 '1006000647': '봉화산',
 '1077000688': '양재',
 '1077000689': '양재시민의숲',
 '1077006810': '청계산입구',
 '1077006811': '판교',
 '1077006812': '정자',
 '1009000926': '언주',
 '1009000927': '선정릉',
 '1009000928': '삼성중앙',
 '1009000929': '봉은사',
 '1009000930': '종합운동장',
 '1065065072': '영종',
 '1063075328': '야당',
 '1067080116': '청량리',
 '1067080117': '회기',
 '1067080118': '중랑',
 '1071075261': '인하대',
 '1077006814': '동천',
 '1077006815': '수지구청',
 '1077006816': '성복',
 '1077006817': '상현',
 '1077006818': '광교중앙',
 '1077006819': '광교',
 '1071075262': '숭의',
 '1071075263': '신포',
 '1071075264': '인천',
 '1079340013': '어룡',
 '1079340014': '송산',
 '1078330027': '운연',
 '1081370001': '판교',
 '1081370002': '이매',
 '1081370003': '삼동',
 '1081370004': '경기광주',
 '1081370005': '초월',
 '1081370006': '곤지암',
 '1081370007': '신둔도예촌',
 '1081370008': '이천',
 '1081370009': '부발',
 '1081370011': '여주',
 '1079340001': '발곡',
 '1079340002': '회룡',
 '1079340003': '범골',
 '1079340005': '의정부시청',
 '1079340006': '흥선',
 '1079340007': '의정부중앙',
 '1079340008': '동오',
 '1079340009': '새말',
 '1079340010': '경기도청북부청사',
 '1079340011': '효자',
 '1079340012': '곤제',
 '1079340015': '탑석',
 '1063075138': '지평',
 '1080350001': '기흥',
 '1080350002': '강남대',
 '1080350003': '지석',
 '1080350004': '어정',
 '1080350005': '동백',
 '1080350006': '초당',
 '1080350007': '삼가',
 '1080350008': '시청·용인대',
 '1080350009': '명지대',
 '1080350010': '김량장',
 '1080350011': '운동장·송담대',
 '1080350012': '고진',
 '1080350013': '보평',
 '1080350014': '둔전',
 '1080350015': '전대·에버랜드',
 '1078330001': '검단오류',
 '1078330002': '왕길',
 '1078330004': '마전',
 '1078330005': '완정',
 '1078330006': '독정',
 '1078330007': '검암',
 '1078330008': '검바위',
 '1078330009': '아시아드경기장',
 '1078330010': '서구청',
 '1078330011': '가정',
 '1078330013': '석남',
 '1078330014': '서부여성회관',
 '1078330015': '인천가좌',
 '1008000810': '암사',
 '1008000811': '천호',
 '1009000901': '개화',
 '1009000902': '김포공항',
 '1009000903': '공항시장',
 '1009000904': '신방화',
 '1009000905': '마곡나루',
 '1009000906': '양천향교',
 '1009000907': '가양',
 '1009000908': '증미',
 '1009000909': '등촌',
 '1009000910': '염창',
 '1009000911': '신목동',
 '1009000912': '선유도',
 '1009000913': '당산',
 '1009000914': '국회의사당',
 '1009000915': '여의도',
 '1009000916': '샛강',
 '1009000917': '노량진',
 '1009000918': '노들',
 '1009000919': '흑석',
 '1009000920': '동작',
 '1009000921': '구반포',
 '1009000922': '신반포',
 '1009000923': '고속터미널',
 '1009000924': '사평',
 '1009000925': '신논현',
 '1007000721': '면목',
 '1007000722': '사가정',
 '1007000723': '용마산',
 '1007000724': '중곡',
 '1001000142': '구일',
 '1001000143': '개봉',
 '1001000144': '오류동',
 '1001000145': '온수',
 '1001000146': '역곡',
 '1001000147': '소사',
 '1001000148': '부천',
 '1001000149': '중동',
 '1001000150': '송내',
 '1001000151': '부개',
 '1001000152': '부평',
 '1001000153': '백운',
 '1001000154': '동암',
 '1001000155': '간석',
 '1001000156': '주안',
 '1001000157': '도화',
 '1001000158': '제물포',
 '1001000159': '도원',
 '1001000160': '동인천',
 '1001000161': '인천',
 '1001075410': '광명',
 '1001080142': '가산디지털단지',
 '1001000101': '동두천',
 '1001000102': '보산',
 '1001000103': '동두천중앙',
 '1001000104': '지행',
 '1001000105': '덕정',
 '1001000106': '덕계',
 '1001000107': '양주',
 '1001000108': '녹양',
 '1001000109': '가능',
 '1001000110': '의정부',
 '1001000111': '회룡',
 '1007000730': '강남구청',
 '1007000731': '학동',
 '1007000732': '논현',
 '1007000733': '반포',
 '1007000734': '고속터미널',
 '1007000735': '내방',
 '1078330017': '주안국가산단',
 '1078330018': '주안',
 '1004000412': '창동',
 '1004000413': '쌍문',
 '1004000414': '수유',
 '1004000415': '미아',
 '1007000710': '도봉산',
 '1007000711': '수락산',
 '1007000712': '마들',
 '1007000713': '노원',
 '1007000714': '중계',
 '1007000715': '하계',
 '1007000716': '공릉',
 '1007000717': '태릉입구',
 '1007000718': '먹골',
 '1007000719': '중화',
 '1007000720': '상봉',
 '1007000736': '총신대입구(이수)',
 '1001080143': '독산',
 '1004000416': '미아사거리',
 '1004000417': '길음',
 '1004000418': '성신여대입구',
 '1004000419': '한성대입구',
 '1004000420': '혜화',
 '1004000421': '동대문',
 '1004000422': '동대문역사문화공원',
 '1004000423': '충무로',
 '1004000424': '명동',
 '1004000425': '회현',
 '1004000426': '서울',
 '1004000427': '숙대입구',
 '1004000428': '삼각지',
 '1004000429': '신용산',
 '1004000430': '이촌',
 '1004000431': '동작',
 '1004000432': '총신대입구(이수)',
 '1004000433': '사당',
 '1004000434': '남태령',
 '1004000435': '선바위',
 '1004000436': '경마공원',
 '1004000437': '대공원',
 '1004000438': '과천',
 '1004000439': '정부과천청사',
 '1004000440': '인덕원',
 '1004000441': '평촌',
 '1004000442': '범계',
 '1004000443': '금정',
 '1004000444': '산본',
 '1004000445': '수리산',
 '1004000446': '대야미',
 '1005000532': '서대문',
 '1005000533': '광화문',
 '1005000534': '종로3가',
 '1005000535': '을지로4가',
 '1005000536': '동대문역사문화공원',
 '1005000537': '청구',
 '1005000538': '신금호',
 '1005000539': '행당',
 '1005000540': '왕십리',
 '1005000541': '마장',
 '1005000542': '답십리',
 '1005000543': '장한평',
 '1005000544': '군자',
 '1005000545': '아차산',
 '1005000546': '광나루',
 '1005000547': '천호',
 '1005000548': '강동',
 '1005000549': '길동',
 '1005000550': '굽은다리',
 '1005000551': '명일',
 '1005000552': '고덕',
 '1005000553': '상일동',
 '1005080549': '둔촌동',
 '1005080550': '올림픽공원',
 '1005080551': '방이',
 '1005080552': '오금',
 '1005080553': '개롱',
 '1005080554': '거여',
 '1005080555': '마천',
 '1006000610': '응암',
 '1006000611': '역촌',
 '1006000612': '불광',
 '1006000613': '독바위',
 '1006000614': '연신내',
 '1006000615': '구산',
 '1006000616': '새절',
 '1006000617': '증산',
 '1006000618': '디지털미디어시티',
 '1006000619': '월드컵경기장',
 '1006000620': '마포구청',
 '1006000621': '망원',
 '1006000622': '합정',
 '1006000623': '상수',
 '1006000624': '광흥창',
 '1006000625': '대흥',
 '1006000626': '공덕',
 '1006000627': '효창공원앞',
 '1006000628': '삼각지',
 '1006000629': '녹사평',
 '1006000630': '이태원',
 '1006000631': '한강진',
 '1006000632': '버티고개',
 '1006000633': '약수',
 '1006000634': '청구',
 '1006000635': '신당',
 '1006000636': '동묘앞',
 '1006000637': '창신',
 '1006000638': '보문',
 '1006000639': '안암',
 '1006000640': '고려대',
 '1006000641': '월곡',
 '1006000642': '상월곡',
 '1006000643': '돌곶이',
 '1006000644': '석계',
 '1006000645': '태릉입구',
 '1002000234': '신도림',
 '1002000235': '문래',
 '1002000236': '영등포구청',
 '1002000237': '당산',
 '1002000238': '합정',
 '1002000239': '홍대입구',
 '1002000240': '신촌',
 '1002000241': '이대',
 '1002000242': '아현',
 '1002000243': '충정로',
 '1002002111': '용답',
 '1002002112': '신답',
 '1002002113': '용두',
 '1002002114': '신설동',
 '1002002341': '도림천',
 '1002002342': '양천구청',
 '1002002343': '신정네거리',
 '1002002344': '까치산',
 '1003000310': '대화',
 '1003000311': '주엽',
 '1003000312': '정발산',
 '1003000313': '마두',
 '1003000314': '백석',
 '1003000315': '대곡',
 '1003000316': '화정',
 '1003000317': '원당',
 '1003000318': '삼송',
 '1003000319': '지축',
 '1003000320': '구파발',
 '1003000321': '연신내',
 '1003000322': '불광',
 '1002000201': '시청',
 '1002000202': '을지로입구',
 '1002000203': '을지로3가',
 '1002000204': '을지로4가',
 '1002000205': '동대문역사문화공원',
 '1002000206': '신당',
 '1002000207': '상왕십리',
 '1002000208': '왕십리',
 '1002000209': '한양대',
 '1002000210': '뚝섬',
 '1002000211': '성수',
 '1002000212': '건대입구',
 '1002000213': '구의',
 '1002000214': '강변',
 '1002000215': '잠실나루',
 '1002000216': '잠실',
 '1002000217': '잠실새내',
 '1002000218': '종합운동장',
 '1002000219': '삼성',
 '1002000220': '선릉',
 '1002000221': '역삼',
 '1002000222': '강남',
 '1002000223': '교대',
 '1002000224': '서초',
 '1002000225': '방배',
 '1002000226': '사당',
 '1002000227': '낙성대',
 '1002000228': '서울대입구',
 '1002000229': '봉천',
 '1002000230': '신림',
 '1002000231': '신대방',
 '1002000232': '구로디지털단지',
 '1004000411': '노원',
 '1001000100': '소요산',
 '1001000133': '서울',
 '1001000134': '남영',
 '1001000135': '용산',
 '1001000136': '노량진',
 '1001000137': '대방',
 '1001000138': '신길',
 '1001000139': '영등포',
 '1001000140': '신도림',
 '1001000141': '구로',
 '1001000112': '망월사',
 '1001000113': '도봉산',
 '1001000114': '도봉',
 '1001000115': '방학',
 '1001000116': '창동',
 '1001000117': '녹천',
 '1001000118': '월계',
 '1001000119': '광운대',
 '1001000120': '석계',
 '1001000121': '신이문',
 '1001000122': '외대앞',
 '1001000123': '회기',
 '1001000124': '청량리',
 '1001000125': '제기동',
 '1001000126': '신설동',
 '1001000127': '동묘앞',
 '1001000128': '동대문',
 '1001000129': '종로5가',
 '1001000130': '종로3가',
 '1001000131': '종각',
 '1001000132': '시청',
 '1009000937': '둔촌오륜',
 '1081370010': '세종대왕릉',
 '1079340004': '경전철의정부',
 '1078330012': '가정중앙시장',
 '1005000554': '강일',
 '1005000555': '미사',
 '1005000556': '하남풍산',
 '1005000557': '하남시청',
 '1005000558': '하남검단산',
 '1075075236': '신갈',
 '1075075237': '기흥',
 '1075075238': '상갈',
 '1075075239': '청명',
 '1075075240': '영통',
 '1075075241': '망포',
 '1075075242': '매탄권선',
 '1075075243': '수원시청',
 '1075075244': '매교',
 '1075075245': '수원',
 '1075075246': '고색',
 '1075075247': '오목천',
 '1075075248': '어천',
 '1075075249': '야목',
 '1075075250': '사리',
 '1075075251': '한대앞',
 '1075075252': '중앙',
 '1075075253': '고잔',
 '1075075254': '초지',
 '1075075255': '안산',
 '1075075256': '신길온천',
 '1075075257': '정왕',
 '1075075258': '오이도',
 '1075075259': '달월',
 '1075075260': '월곶',
 '1075075261': '소래포구',
 '1075075262': '인천논현',
 '1075075263': '호구포',
 '1075075264': '남동인더스파크',
 '1075075265': '원인재',
 '1075075266': '연수',
 '1075075267': '송도',
 '1075075268': '인하대',
 '1075075269': '숭의',
 '1001080173': '탕정',
 '1075075270': '신포',
 '1075075271': '인천',
 '1008000820': '복정',
 '1008000821': '남위례',
 '1008000822': '산성',
 '1008000823': '남한산성입구',
 '1008000824': '단대오거리',
 '1008000825': '신흥',
 '1008000826': '수진',
 '1008000827': '모란',
 '1007000760': '산곡',
 '1007000761': '석남',
 '1069073139': '송도달빛축제공원',
 '1006000648': '신내',
 '1001080141': '광명'}

In [9]:
statn['이전역'] = ''
statn['다음역'] = ''

for index, row in statn.iterrows():
    row['이전역'] = statn_dict[row['이전지하철역ID']]
    row['다음역'] = statn_dict[row['다음지하철역ID']]

statn = statn.loc[:,['지하철역ID','지하철호선ID','지하철역명','이전역','다음지하철역ID','다음역']]
statn

         지하철역ID 지하철호선ID     지하철역명     이전역    다음지하철역ID       다음역
0    1009000931    1009        삼전   종합운동장  1009000932      석촌고분
1    1009000932    1009      석촌고분      삼전  1009000933        석촌
2    1009000933    1009        석촌    석촌고분  1009000934      송파나루
3    1009000934    1009      송파나루      석촌  1009000935      한성백제
4    1009000935    1009      한성백제    송파나루  1009000936     올림픽공원
..          ...     ...       ...     ...         ...       ...
754  1008000827    1008        모란      수진  1008000827        모란
755  1007000760    1007        산곡    부평구청  1007000760        산곡
756  1007000761    1007        석남      산곡  1007000761        석남
757  1069073139    1069  송도달빛축제공원  국제업무지구  1069073139  송도달빛축제공원
758  1006000648    1006        신내     봉화산  1006000648        신내

[759 rows x 6 columns]

In [10]:
statn[statn['지하철호선ID']=='1004']

         지하철역ID 지하철호선ID      지하철역명        이전역    다음지하철역ID        다음역
275  1004000409    1004        당고개        당고개  1004000410         상계
276  1004000410    1004         상계        당고개  1004000411         노원
309  1004000447    1004         반월        대야미  1004000448        상록수
310  1004000448    1004        상록수         반월  1004000449        한대앞
311  1004000449    1004        한대앞        상록수  1004000450         중앙
312  1004000450    1004         중앙        한대앞  1004000451         고잔
313  1004000451    1004         고잔         중앙  1004000452         초지
314  1004000452    1004         초지         고잔  1004000453         안산
315  1004000453    1004         안산         초지  1004000454       신길온천
316  1004000454    1004       신길온천         안산  1004000455         정왕
317  1004000455    1004         정왕       신길온천  1004000456        오이도
318  1004000456    1004        오이도         정왕  1004000456        오이도
493  1004000412    1004         창동         노원  1004000413         쌍문
494  1004000413    1004         쌍문         창동  1004000414         수유
495  1004000414    1004         수유         쌍문  1004000415         미아
496  1004000415    1004         미아         수유  1004000416      미아사거리
510  1004000416    1004      미아사거리         미아  1004000417         길음
511  1004000417    1004         길음      미아사거리  1004000418     성신여대입구
512  1004000418    1004     성신여대입구         길음  1004000419      한성대입구
513  1004000419    1004      한성대입구     성신여대입구  1004000420         혜화
514  1004000420    1004         혜화      한성대입구  1004000421        동대문
515  1004000421    1004        동대문         혜화  1004000422  동대문역사문화공원
516  1004000422    1004  동대문역사문화공원        동대문  1004000423        충무로
517  1004000423    1004        충무로  동대문역사문화공원  1004000424         명동
518  1004000424    1004         명동        충무로  1004000425         회현
519  1004000425    1004         회현         명동  1004000426         서울
520  1004000426    1004         서울         회현  1004000427       숙대입구
521  1004000427    1004       숙대입구         서울  1004000428        삼각지
522  1004000428    1004        삼각지       숙대입구  1004000429        신용산
523  1004000429    1004        신용산        삼각지  1004000430         이촌
524  1004000430    1004         이촌        신용산  1004000431         동작
525  1004000431    1004         동작         이촌  1004000432  총신대입구(이수)
526  1004000432    1004  총신대입구(이수)         동작  1004000433         사당
527  1004000433    1004         사당  총신대입구(이수)  1004000434        남태령
528  1004000434    1004        남태령         사당  1004000435        선바위
529  1004000435    1004        선바위        남태령  1004000436       경마공원
530  1004000436    1004       경마공원        선바위  1004000437        대공원
531  1004000437    1004        대공원       경마공원  1004000438         과천
532  1004000438    1004         과천        대공원  1004000439     정부과천청사
533  1004000439    1004     정부과천청사         과천  1004000440        인덕원
534  1004000440    1004        인덕원     정부과천청사  1004000441         평촌
535  1004000441    1004         평촌        인덕원  1004000442         범계
536  1004000442    1004         범계         평촌  1004000443         금정
537  1004000443    1004         금정         범계  1004000444         산본
538  1004000444    1004         산본         금정  1004000445        수리산
539  1004000445    1004        수리산         산본  1004000446        대야미
540  1004000446    1004        대야미        수리산  1004000447         반월
669  1004000411    1004         노원         상계  1004000412         창동

In [11]:
statn['지하철호선명'] = ''

for idx, row in statn.iterrows():
	if row.지하철호선ID	 == '1009':
		row.지하철호선명 = '9호선'
	elif row.지하철호선ID	 == '1078':
		row.지하철호선명 = '인천2호선'
	elif row.지하철호선ID	 == '1092':
		row.지하철호선명 = '우이신설'
	elif row.지하철호선ID	 == '1067':
		row.지하철호선명 = '경춘'
	elif row.지하철호선ID	 == '1069':
		row.지하철호선명 = '인천1호선'
	elif row.지하철호선ID	 == '1003':
		row.지하철호선명 = '3호선'
	elif row.지하철호선ID	 == '1063':
		row.지하철호선명 = '경의'
	elif row.지하철호선ID	 == '1065':
		row.지하철호선명 = '공항철도'
		
	elif row.지하철호선ID	 == '1071':
		row.지하철호선명 = '수인분당'
	elif row.지하철호선ID	 == '1091':
		row.지하철호선명 = '자기부상철도'
	elif row.지하철호선ID	 == '1075':
		row.지하철호선명 = '수인분당'
	elif row.지하철호선ID	 == '1077':
		row.지하철호선명 = '신분당'
	elif row.지하철호선ID	 == '1093':
		row.지하철호선명 = '서해선'
	elif row.지하철호선ID	 == '1001':
		row.지하철호선명 = '1호선'
	elif row.지하철호선ID	 == '1002':
		row.지하철호선명 = '2호선'
	elif row.지하철호선ID	 == '1007':
		row.지하철호선명 = '7호선'
		
	elif row.지하철호선ID	 == '1004':
		row.지하철호선명 = '4호선'
	elif row.지하철호선ID	 == '1008':
		row.지하철호선명 = '8호선'
	elif row.지하철호선ID	 == '1006':
		row.지하철호선명 = '6호선'
	elif row.지하철호선ID	 == '1005':
		row.지하철호선명 = '5호선'
	elif row.지하철호선ID	 == '1079':
		row.지하철호선명 = '의정부경전철'
	elif row.지하철호선ID	 == '1081':
		row.지하철호선명 = '신분당'
	elif row.지하철호선ID	 == '1080':
		row.지하철호선명 = '에버라인'

In [12]:
df_before = statn[['지하철호선명','지하철역명','지하철호선명','이전역']]
df_before['상하행'] = '하행'
df_before['weight'] = 1
df_before.columns = ['선명','역명칭','환승선명','환승이후역명','상하행','weight']
df_after = statn[['지하철호선명','지하철역명','지하철호선명','다음역']]
df_after['상하행'] = '상행'
df_after['weight'] = 1
df_after.columns = ['선명','역명칭','환승선명','환승이후역명','상하행','weight']

df3 = pd.concat([df_before,df_after], axis = 0)
df3

<ipython-input-12-ee949ac9c758>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_before['상하행'] = '하행'
<ipython-input-12-ee949ac9c758>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_before['weight'] = 1
<ipython-input-12-ee949ac9c758>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_after['상하행'] = '상행'
<ipython-input-12-ee949ac9c758>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_after['weight'] = 1

        선명       역명칭   환승선명    환승이후역명 상하행  weight
0      9호선        삼전    9호선     종합운동장  하행       1
1      9호선      석촌고분    9호선        삼전  하행       1
2      9호선        석촌    9호선      석촌고분  하행       1
3      9호선      송파나루    9호선        석촌  하행       1
4      9호선      한성백제    9호선      송파나루  하행       1
..     ...       ...    ...       ...  ..     ...
754    8호선        모란    8호선        모란  상행       1
755    7호선        산곡    7호선        산곡  상행       1
756    7호선        석남    7호선        석남  상행       1
757  인천1호선  송도달빛축제공원  인천1호선  송도달빛축제공원  상행       1
758    6호선        신내    6호선        신내  상행       1

[1518 rows x 6 columns]

In [15]:
df3[df3['선명']=='2호선']

      선명      역명칭 환승선명   환승이후역명 상하행  weight
238  2호선       대림  2호선  구로디지털단지  하행       1
606  2호선      신도림  2호선       대림  하행       1
607  2호선       문래  2호선      신도림  하행       1
608  2호선    영등포구청  2호선       문래  하행       1
609  2호선       당산  2호선    영등포구청  하행       1
..   ...      ...  ...      ...  ..     ...
664  2호선    서울대입구  2호선       봉천  상행       1
665  2호선       봉천  2호선       신림  상행       1
666  2호선       신림  2호선      신대방  상행       1
667  2호선      신대방  2호선  구로디지털단지  상행       1
668  2호선  구로디지털단지  2호선       대림  상행       1

[102 rows x 6 columns]

In [27]:
df =  pd.read_csv('/content/drive/MyDrive/Hackathon/Chuldong/서울시장애인지하철편의시설정보.csv', encoding='cp949')
df1 =  pd.read_csv('/content/drive/MyDrive/Hackathon/Chuldong/국가철도공단_서울메트로_환승정보_20221122.csv', encoding='cp949')
df

,고유번호,노선,노선명칭,역명칭,역 이미지,운행방향1,운행방향2,엘레베이터 동영상,엘리베이터 자막,지아철 팝업 이미지,사용여부,편의시설 아이콘 이미지 목록,출구정보,전화번호안내,코스1 첫차,코스1 막차,코스2 첫차,코스2 막차
0,369,9,분당선,개포동,<img src='https://wis.eseoul.go.kr/images/disa...,선릉,보정,NaN,NaN,<img src='https://wis.eseoul.go.kr/images/disa...,Y,NaN,NaN,긴급전화(역무실) : 02-3412-4418,개포동 : 05시39분,개포동 : 24시04분,개포동 : 05시32분,개포동 : 24시00분
1,2,1,1호선,두정,<img src='https://wis.eseoul.go.kr/images/disa...,구로,천안,NaN,NaN,<img src='https://wis.eseoul.go.kr/images/disa...,Y,NaN,NaN,긴급전화(역무실) : 041-562-7791,두정 : 05시04분,두정 : 23시44분,두정 : 05시45분,두정 : 24시30분
2,4,1,1호선,성환,<img src='https://wis.eseoul.go.kr/images/disa...,구로,천안,NaN,NaN,<img src='https://wis.eseoul.go.kr/images/disa...,Y,NaN,NaN,긴급전화(역무실) : 041-581-7788,성환 : 05시13분,성환 : 23시53분,성환 : 05시36분,성환 : 24시21분
3,5,1,1호선,평택,<img src='https://wis.eseoul.go.kr/images/disa...,구로,천안,NaN,NaN,<img src='https://wis.eseoul.go.kr/images/disa...,Y,NaN,NaN,긴급전화(역무실) : 031-652-7811,평택 : 05시20분,평택 : 24시00분,평택 : 05시29분,평택 : 24시13분
4,6,1,1호선,지제,<img src='https://wis.eseoul.go.kr/images/disa...,구로,천안,NaN,NaN,<img src='https://wis.eseoul.go.kr/images/disa...,Y,NaN,NaN,긴급전화(역무실) : 1544-7788,지제 : 05시25분,지제 : 24시05분,지제 : 05시24분,지제 : 24시09분
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,13,1,1호선,병점,<img src='https://wis.eseoul.go.kr/images/disa...,구로,천안,NaN,NaN,<img src='https://wis.eseoul.go.kr/images/disa...,Y,NaN,NaN,긴급전화(역무실) : 031-234-7788,병점 : 05시04분,병점 : 23시43분,병점 : 05시00분,병점 : 23시44분
453,44,1,1호선,오류동,<img src='https://wis.eseoul.go.kr/images/disa...,소요산,인천,NaN,NaN,<img src='https://wis.eseoul.go.kr/images/disa...,Y,NaN,"||1@오류1동지역||,||2@오류2동지역||",긴급전화(역무실) : 02-2685-7788,오류동 : 05시21분,오류동 : 24시23분,오류동 : 05시07분,오류동 : 23시54분
454,138,3,3호선,원당,<img src='https://wis.eseoul.go.kr/images/disa...,대화,수서,NaN,NaN,<img src='https://wis.eseoul.go.kr/images/disa...,Y,NaN,"||1@원당농협성래지소||,||2@원당농협성래지소||,||3@약수터||,||4@고양...",긴급전화(역무실) : 031-965-8747,원당 : 05시21분,원당 : 24시40분,원당 : 05시34분,원당 : 24시56분
455,453,13,9호선,신반포,<img src='https://wis.eseoul.go.kr/images/disa...,개화,신논현,NaN,NaN,<img src='https://wis.eseoul.go.kr/images/disa...,Y,<img src='http://wis.seoul.go.kr/images/disabl...,"||1@반포2동 주민센터, 반포우체국||,||2@신반포 중학교, 계성 초등학교||,...",긴급전화(역무실) : 02-2656-0922,신반포 : 05시44분,신반포 : 24시46분,신반포 : 05시49분,신반포 : 24시56분
456,188,4,4호선,서울역,<img src='https://wis.eseoul.go.kr/images/disa...,당고개,오이도,http://wis.seoul.go.kr/rest/file/thumbnail/yf1...,승강기 위치는 12번 출구쪽에 있습니다. 승강기를 이용하여 지하 1층 대합...,<img src='https://wis.eseoul.go.kr/images/disa...,Y,<img src='http://wis.seoul.go.kr/images/disabl...,"||1@벽산125빌딩,LG역전빌딩,남대문경찰서||,||2@대일학원,경일학원,한일은행...",긴급전화(역무실) : 02-6110-4261,서울역 : 05시33분,서울역 : 24시26분,서울역 : 05시50분,서울역 : 23시43분

In [28]:
df1

    철도운영기관명   선명            역명 환승철도운영기관  환승선명 환승이후역명 환승기점역명  차량순서  차량출입문번호
0    서울교통공사  1호선  청량리(서울시립대입구)      코레일  경의중앙    왕십리     용산    10        4
1    서울교통공사  1호선  청량리(서울시립대입구)      코레일  경의중앙     회기     문산     1        1
2    서울교통공사  1호선  청량리(서울시립대입구)      코레일  경의중앙    왕십리     용산     1        1
3    서울교통공사  1호선  청량리(서울시립대입구)      코레일  경의중앙     회기     문산    10        4
4    서울교통공사  1호선           신설동   서울교통공사   2호선     용두     성수     9        4
..      ...  ...           ...      ...   ...    ...    ...   ...      ...
476  서울교통공사  8호선            복정      코레일  수인분당    가천대     수원     4        2
477  서울교통공사  8호선            복정      코레일  수인분당     수서    왕십리     4        2
478  서울교통공사  8호선            복정      코레일  수인분당    가천대     수원     3        2
479  서울교통공사  8호선            모란      코레일  수인분당     태평    왕십리     1        1
480  서울교통공사  8호선            모란      코레일  수인분당     야탑     수원     1        1

[481 rows x 9 columns]

In [29]:
df = df.loc[:,['고유번호','노선','노선명칭','역명칭']]
df1.columns = ['철도운영기관명', '선명', '역명칭', '환승철도운영기관', '환승선명', '환승이후역명', '환승기점역명', '차량순서', '차량출입문번호']
df1.merge(df,'left',on='역명칭')
df1

    철도운영기관명   선명           역명칭 환승철도운영기관  환승선명 환승이후역명 환승기점역명  차량순서  차량출입문번호
0    서울교통공사  1호선  청량리(서울시립대입구)      코레일  경의중앙    왕십리     용산    10        4
1    서울교통공사  1호선  청량리(서울시립대입구)      코레일  경의중앙     회기     문산     1        1
2    서울교통공사  1호선  청량리(서울시립대입구)      코레일  경의중앙    왕십리     용산     1        1
3    서울교통공사  1호선  청량리(서울시립대입구)      코레일  경의중앙     회기     문산    10        4
4    서울교통공사  1호선           신설동   서울교통공사   2호선     용두     성수     9        4
..      ...  ...           ...      ...   ...    ...    ...   ...      ...
476  서울교통공사  8호선            복정      코레일  수인분당    가천대     수원     4        2
477  서울교통공사  8호선            복정      코레일  수인분당     수서    왕십리     4        2
478  서울교통공사  8호선            복정      코레일  수인분당    가천대     수원     3        2
479  서울교통공사  8호선            모란      코레일  수인분당     태평    왕십리     1        1
480  서울교통공사  8호선            모란      코레일  수인분당     야탑     수원     1        1

[481 rows x 9 columns]

In [38]:
df1[df1['역명칭']=='사당']

    철도운영기관명   선명 역명칭 환승철도운영기관 환승선명     환승이후역명      환승기점역명  차량순서  차량출입문번호
90   서울교통공사  2호선  사당   서울교통공사  4호선  총신대입구(이수)         당고개     5        3
91   서울교통공사  2호선  사당   서울교통공사  4호선        남태령         남태령     5        3
92   서울교통공사  2호선  사당   서울교통공사  4호선  총신대입구(이수)         당고개     6        1
93   서울교통공사  2호선  사당   서울교통공사  4호선        남태령         남태령     6        1
248  서울교통공사  4호선  사당   서울교통공사  2호선         방배          시청    10        4
249  서울교통공사  4호선  사당   서울교통공사  2호선        낙성대  충정로(경기대입구)     4        2
250  서울교통공사  4호선  사당   서울교통공사  2호선         방배          시청     1        1
251  서울교통공사  4호선  사당   서울교통공사  2호선        낙성대  충정로(경기대입구)     7        3

In [39]:
df3[df3['역명칭']=='사당']

      선명 역명칭 환승선명     환승이후역명 상하행  weight
527  4호선  사당  4호선  총신대입구(이수)  하행       1
662  2호선  사당  2호선         방배  하행       1
527  4호선  사당  4호선        남태령  상행       1
662  2호선  사당  2호선        낙성대  상행       1

In [35]:
line = {
    '1호선':1,
    '2호선':2,
    '3호선':3,
    '4호선':4,
    '5호선':5,
    '6호선':6,
    '7호선':7,
    '8호선':8,
    '9호선':9,
    '인천1호선':11,
    '인천2호선':12,
    '경의중앙':21,
    '우이신설':22,
    '공항철도':23,
    '경춘':24,
    '수인분당':25,
    '신분당선':33,
    '수인선':32,
    '서해선':31,
    '경의':41,
    '자기부상철도':42,
    '신분당':43,
    '의정부경전철':44,
    '에버라인':45
}

In [36]:
df2 = df1.loc[:,['선명','역명칭','환승선명','환승이후역명','환승기점역명']]

df2.head()

    선명           역명칭  환승선명 환승이후역명 환승기점역명
0  1호선  청량리(서울시립대입구)  경의중앙    왕십리     용산
1  1호선  청량리(서울시립대입구)  경의중앙     회기     문산
2  1호선  청량리(서울시립대입구)  경의중앙    왕십리     용산
3  1호선  청량리(서울시립대입구)  경의중앙     회기     문산
4  1호선           신설동   2호선     용두     성수

In [37]:
df3.head()

    선명   역명칭 환승선명 환승이후역명 상하행  weight
0  9호선    삼전  9호선  종합운동장  하행       1
1  9호선  석촌고분  9호선     삼전  하행       1
2  9호선    석촌  9호선   석촌고분  하행       1
3  9호선  송파나루  9호선     석촌  하행       1
4  9호선  한성백제  9호선   송파나루  하행       1

In [32]:
df2 = df1.loc[:,['선명','역명칭','환승선명','환승이후역명','환승기점역명']]
df2['weight'] = 1
df2 = pd.concat([df2,df3],axis=0)
df2 = df2.dropna()
df2['환승이후역명'][df2['환승이후역명']=='녹사평(용산구청)'] = '녹사평'
df2['환승이후역명'][df2['환승이후역명']=='선정릉(한국과학창의재단)'] = '선정릉'
df2['환승이후역명'][df2['환승이후역명']=='대흥(서강대앞)'] = '대흥'
df2['환승이후역명'][df2['환승이후역명']=='복정(동서울대학)'] = '복정'
df2['환승이후역명'][df2['환승이후역명']=='어린이대공원(세종대)'] = '어린이대공원'
df2['환승이후역명'][df2['환승이후역명']=='구의(광진구청)'] = '구의'
df2['환승이후역명'][df2['환승이후역명']=='공릉(서울과학기술대)'] = '공릉'
df2['환승이후역명'][df2['환승이후역명']=='화랑대(서울여대입구)'] = '화랑대'
df2['환승이후역명'][df2['환승이후역명']=='회현(남대문시장)'] = '회현'
df2['환승이후역명'][df2['환승이후역명']=='숙대입구(갈월)'] = '숙대입구'


df2[df2['환승이후역명'].str.contains('\(')]
df2 = df2.loc[:,['선명','역명칭','환승선명','환승이후역명','환승기점역명','weight']]
df2.drop_duplicates(inplace=True)

<ipython-input-32-c054b87c6087>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['환승이후역명'][df2['환승이후역명']=='선정릉(한국과학창의재단)'] = '선정릉'
<ipython-input-32-c054b87c6087>:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['환승이후역명'][df2['환승이후역명']=='대흥(서강대앞)'] = '대흥'
<ipython-input-32-c054b87c6087>:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['환승이후역명'][df2['환승이후역명']=='복정(동서울대학)'] = '복정'
<ipython-input-32-c054b87c6087>:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['환승이후역명'][df2['환승이후역명']=='어린이대공원(세종대)'] = '어린이대공원'
<ipython-input-32-c054b87c6087>:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['환승이후역명'][df2['환승이후역명']=='구의(광진구청)'] = '구의'
<ipython-input-32-c054b87c6087>:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['환승이후역명'][df2['환승이후역명']=='공릉(서울과학기술대)'] = '공릉'
<ipython-input-32-c054b87c6087>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['환승이후역명'][df2['환승이후역명']=='화랑대(서울여대입구)'] = '화랑대'
<ipython-input-32-c054b87c6087>:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['환승이후역명'][df2['환승이후역명']=='회현(남대문시장)'] = '회현'
<ipython-input-32-c054b87c6087>:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['환승이후역명'][df2['환승이후역명']=='숙대입구(갈월)'] = '숙대입구'

Empty DataFrame
Columns: [선명, 역명칭, 환승선명, 환승이후역명, 환승기점역명, weight]
Index: []

In [40]:
df3

        선명       역명칭   환승선명    환승이후역명 상하행  weight
0      9호선        삼전    9호선     종합운동장  하행       1
1      9호선      석촌고분    9호선        삼전  하행       1
2      9호선        석촌    9호선      석촌고분  하행       1
3      9호선      송파나루    9호선        석촌  하행       1
4      9호선      한성백제    9호선      송파나루  하행       1
..     ...       ...    ...       ...  ..     ...
754    8호선        모란    8호선        모란  상행       1
755    7호선        산곡    7호선        산곡  상행       1
756    7호선        석남    7호선        석남  상행       1
757  인천1호선  송도달빛축제공원  인천1호선  송도달빛축제공원  상행       1
758    6호선        신내    6호선        신내  상행       1

[1518 rows x 6 columns]

In [41]:
df3['엘리베이터'] = ''
df3['리프트'] = ''
df3['휠체어경사로'] =''
df3['전화번호'] = ''
df3

        선명       역명칭   환승선명    환승이후역명 상하행  weight 엘리베이터 리프트 휠체어경사로 전화번호
0      9호선        삼전    9호선     종합운동장  하행       1
1      9호선      석촌고분    9호선        삼전  하행       1
2      9호선        석촌    9호선      석촌고분  하행       1
3      9호선      송파나루    9호선        석촌  하행       1
4      9호선      한성백제    9호선      송파나루  하행       1
..     ...       ...    ...       ...  ..     ...   ...  ..    ...  ...
754    8호선        모란    8호선        모란  상행       1
755    7호선        산곡    7호선        산곡  상행       1
756    7호선        석남    7호선        석남  상행       1
757  인천1호선  송도달빛축제공원  인천1호선  송도달빛축제공원  상행       1
758    6호선        신내    6호선        신내  상행       1

[1518 rows x 10 columns]

In [42]:
df2 = df3[:]

In [ ]:
#df2.to_csv('환승경우의수.csv', index=False,encoding='cp949')  # index=False로 설정하여 인덱스를 저장하지 않음

## 엘리베이터 여부 반영

In [46]:
EV_Line_1_Df =  pd.read_csv('/content/drive/MyDrive/Hackathon/Chuldong/국가철도공단_수도권1호선_엘리베이터_20221122.csv', encoding='cp949')
EV_Line_2_Df = pd.read_csv('/content/drive/MyDrive/Hackathon/Chuldong/국가철도공단_수도권2호선_엘리베이터_20221122.csv', encoding='cp949')
EV_Line_3_Df = pd.read_csv('/content/drive/MyDrive/Hackathon/Chuldong/국가철도공단_수도권3호선_엘리베이터_20221122.csv', encoding='cp949')
EV_Line_4_Df = pd.read_csv('/content/drive/MyDrive/Hackathon/Chuldong/국가철도공단_수도권4호선_엘리베이터_20221122.csv', encoding='cp949')
EV_Line_5_Df = pd.read_csv('/content/drive/MyDrive/Hackathon/Chuldong/국가철도공단_수도권5호선_엘리베이터_20221122.csv', encoding='cp949')
EV_Line_6_Df = pd.read_csv('/content/drive/MyDrive/Hackathon/Chuldong/국가철도공단_수도권6호선_엘리베이터_20221122.csv', encoding='cp949')
EV_Line_7_Df = pd.read_csv('/content/drive/MyDrive/Hackathon/Chuldong/국가철도공단_수도권7호선_엘리베이터_20221122.csv', encoding='cp949')
EV_Line_8_Df = pd.read_csv('/content/drive/MyDrive/Hackathon/Chuldong/국가철도공단_수도권8호선_엘리베이터_20221122.csv', encoding='cp949')
EV_Line_Gyeongui_Jungang_Df = pd.read_csv('/content/drive/MyDrive/Hackathon/Chuldong/국가철도공단_경의중앙선_승강장_정보_20221013.csv', encoding='cp949')
EV_Line_Gyeongchun_Df = pd.read_csv('/content/drive/MyDrive/Hackathon/Chuldong/국가철도공단_경춘선_승강장_정보_20221013.csv', encoding='cp949')
EV_Line_Suin_Bundang_Df = pd.read_csv('/content/drive/MyDrive/Hackathon/Chuldong/국가철도공단_수인분당선_승강장_정보_20221121.csv', encoding='cp949')
EV_Line_New_Bundang_Df = pd.read_csv('/content/drive/MyDrive/Hackathon/Chuldong/국가철도공단_신분당선_승강장_정보_20221013.csv', encoding='cp949')
EV_Line_Ever_Df = pd.read_csv('/content/drive/MyDrive/Hackathon/Chuldong/국가철도공단_에버라인_승강장_정보_20221013.csv', encoding='cp949')
EV_Line_Uijeongbu_Rail_Df = pd.read_csv('/content/drive/MyDrive/Hackathon/Chuldong/국가철도공단_의정부경전철_승강장_정보_20221013.csv', encoding='cp949')
EV_Line_Incheon1_Df = pd.read_csv('/content/drive/MyDrive/Hackathon/Chuldong/국가철도공단_인천1호선_승강장_정보_20221013.csv', encoding='cp949')
EV_Line_Incheon2_Df = pd.read_csv('/content/drive/MyDrive/Hackathon/Chuldong/국가철도공단_인천2호선_승강장_정보_20221013.csv', encoding='cp949')

#### 1~8호선 까지는 반복문 처리

In [47]:
import re

# EV_Line_1_Df부터 EV_Line_8_Df까지 반복
for i in range(1, 9):
    # EV_Line_1_Df, EV_Line_2_Df, ..., EV_Line_8_Df 변수명 생성
    ev_line_df = globals().get(f"EV_Line_{i}_Df")

    # "역명" 컬럼 중복 제거 및 컬럼 이름 변경
    ev_line_df = ev_line_df.drop_duplicates(subset='역명')
    ev_line_df.rename(columns={'역명': '역명칭'}, inplace=True)
    ev_line_df = ev_line_df[['선명', '역명칭']]

    # "역명칭" 컬럼 값이 일치하는 인덱스 검색
    matching_indices = []
    for index, row in df2.iterrows():
        station_name = row['역명칭']
        pattern = r"\b{}\b".format(station_name.replace("(", r"\(").replace(")", r"\)"))
        regex = re.compile(pattern)
        if any(regex.search(station) for station in ev_line_df['역명칭']):
            matching_indices.append(index)

    # 일치하는 인덱스에 대해 "엘리베이터" 컬럼에 1 표시
    df2.loc[matching_indices, '엘리베이터'] = 1

<ipython-input-47-028c7efaf0e5>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ev_line_df.rename(columns={'역명': '역명칭'}, inplace=True)
<ipython-input-47-028c7efaf0e5>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ev_line_df.rename(columns={'역명': '역명칭'}, inplace=True)
<ipython-input-47-028c7efaf0e5>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ev_line_df.rename(columns={'역명': '역명칭'}, inplace=True)
<ipython-input-47-028c7efaf0e5>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ev_line_df.rename(columns={'역명': '역명칭'}, inplace=True)
<ipython-input-47-028c7efaf0e5>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ev_line_df.rename(columns={'역명': '역명칭'}, inplace=True)
<ipython-input-47-028c7efaf0e5>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ev_line_df.rename(columns={'역명': '역명칭'}, inplace=True)
<ipython-input-47-028c7efaf0e5>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ev_line_df.rename(columns={'역명': '역명칭'}, inplace=True)
<ipython-input-47-028c7efaf0e5>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ev_line_df.rename(columns={'역명': '역명칭'}, inplace=True)

In [48]:
df2.head(40)

       선명       역명칭   환승선명  환승이후역명 상하행  weight 엘리베이터 리프트 휠체어경사로 전화번호
0     9호선        삼전    9호선   종합운동장  하행       1
1     9호선      석촌고분    9호선      삼전  하행       1
2     9호선        석촌    9호선    석촌고분  하행       1     1
3     9호선      송파나루    9호선      석촌  하행       1
4     9호선      한성백제    9호선    송파나루  하행       1
5     9호선     올림픽공원    9호선    한성백제  하행       1     1
6     9호선    중앙보훈병원    9호선    둔촌오륜  하행       1
7   인천2호선       가재울  인천2호선    인천가좌  하행       1
8    우이신설        정릉   우이신설  북한산보국문  하행       1
9   인천2호선      시민공원  인천2호선      주안  하행       1
10  인천2호선     석바위시장  인천2호선    시민공원  하행       1
11  인천2호선      인천시청  인천2호선   석바위시장  하행       1
12  인천2호선     석천사거리  인천2호선    인천시청  하행       1
13  인천2호선     모래내시장  인천2호선   석천사거리  하행       1
14  인천2호선        만수  인천2호선   모래내시장  하행       1
15  인천2호선      남동구청  인천2호선      만수  하행       1
16  인천2호선     인천대공원  인천2호선    남동구청  하행       1
17     경춘       천마산     경춘    평내호평  하행       1
18     경춘        마석     경춘     천마산  하행       1
19     경춘       대성리     경춘      마석  하행       1
20     경춘        청평     경춘     대성리  하행       1
21     경춘        상천     경춘      청평  하행       1
22     경춘        가평     경춘      상천  하행       1
23     경춘       굴봉산     경춘      가평  하행       1
24     경춘       백양리     경춘     굴봉산  하행       1
25     경춘        강촌     경춘     백양리  하행       1
26     경춘       김유정     경춘      강촌  하행       1
27     경춘       남춘천     경춘     김유정  하행       1
28     경춘        춘천     경춘     남춘천  하행       1
29  인천1호선        계양  인천1호선      계양  하행       1
30  인천1호선        귤현  인천1호선      계양  하행       1
31  인천1호선        박촌  인천1호선      귤현  하행       1
32  인천1호선        임학  인천1호선      박촌  하행       1
33  인천1호선        계산  인천1호선      임학  하행       1
34    3호선        원흥    3호선      원당  하행       1     1
35     경의        강매     경의      행신  하행       1
36   공항철도        서울   공항철도      서울  하행       1
37   공항철도        공덕   공항철도      서울  하행       1     1
38   공항철도      홍대입구   공항철도      공덕  하행       1     1
39   공항철도  디지털미디어시티   공항철도    홍대입구  하행       1     1

In [49]:
EV_Line_Gyeongui_Jungang_Df = EV_Line_Gyeongui_Jungang_Df.drop_duplicates(subset='역명')
EV_Line_Gyeongui_Jungang_Df.rename(columns={'역명': '역명칭'}, inplace=True)
EV_Line_Gyeongui_Jungang_Df = EV_Line_Gyeongui_Jungang_Df[['선명', '역명칭']]

EV_Line_Gyeongchun_Df = EV_Line_Gyeongchun_Df.drop_duplicates(subset='역명')
EV_Line_Gyeongchun_Df.rename(columns={'역명': '역명칭'}, inplace=True)
EV_Line_Gyeongchun_Df = EV_Line_Gyeongchun_Df[['선명', '역명칭']]

EV_Line_Suin_Bundang_Df = EV_Line_Suin_Bundang_Df.drop_duplicates(subset='역명')
EV_Line_Suin_Bundang_Df.rename(columns={'역명': '역명칭'}, inplace=True)
EV_Line_Suin_Bundang_Df = EV_Line_Suin_Bundang_Df[['선명', '역명칭']]

EV_Line_New_Bundang_Df = EV_Line_New_Bundang_Df.drop_duplicates(subset='역명')
EV_Line_New_Bundang_Df.rename(columns={'역명': '역명칭'}, inplace=True)
EV_Line_New_Bundang_Df = EV_Line_New_Bundang_Df[['선명', '역명칭']]

EV_Line_Ever_Df = EV_Line_Ever_Df.drop_duplicates(subset='역명')
EV_Line_Ever_Df.rename(columns={'역명': '역명칭'}, inplace=True)
EV_Line_Ever_Df = EV_Line_Ever_Df[['선명', '역명칭']]

EV_Line_Uijeongbu_Rail_Df = EV_Line_Uijeongbu_Rail_Df.drop_duplicates(subset='역명')
EV_Line_Uijeongbu_Rail_Df.rename(columns={'역명': '역명칭'}, inplace=True)
EV_Line_Uijeongbu_Rail_Df = EV_Line_Uijeongbu_Rail_Df[['선명', '역명칭']]

EV_Line_Incheon1_Df = EV_Line_Incheon1_Df.drop_duplicates(subset='역명')
EV_Line_Incheon1_Df.rename(columns={'역명': '역명칭'}, inplace=True)
EV_Line_Incheon1_Df = EV_Line_Incheon1_Df[['선명', '역명칭']]

EV_Line_Incheon2_Df = EV_Line_Incheon2_Df.drop_duplicates(subset='역명')
EV_Line_Incheon2_Df.rename(columns={'역명': '역명칭'}, inplace=True)
EV_Line_Incheon2_Df = EV_Line_Incheon2_Df[['선명', '역명칭']]

<ipython-input-49-7a9fa659a59f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  EV_Line_Gyeongui_Jungang_Df.rename(columns={'역명': '역명칭'}, inplace=True)
<ipython-input-49-7a9fa659a59f>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  EV_Line_Gyeongchun_Df.rename(columns={'역명': '역명칭'}, inplace=True)
<ipython-input-49-7a9fa659a59f>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  EV_Line_Suin_Bundang_Df.rename(columns={'역명': '역명칭'}, inplace=True)
<ipython-input-49-7a9fa659a59f>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  EV_Line_New_Bundang_Df.rename(columns={'역명': '역명칭'}, inplace=True)
<ipython-input-49-7a9fa659a59f>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  EV_Line_Ever_Df.rename(columns={'역명': '역명칭'}, inplace=True)
<ipython-input-49-7a9fa659a59f>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  EV_Line_Uijeongbu_Rail_Df.rename(columns={'역명': '역명칭'}, inplace=True)
<ipython-input-49-7a9fa659a59f>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  EV_Line_Incheon1_Df.rename(columns={'역명': '역명칭'}, inplace=True)
<ipython-input-49-7a9fa659a59f>:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  EV_Line_Incheon2_Df.rename(columns={'역명': '역명칭'}, inplace=True)

In [50]:
import re

# "역명칭" 컬럼 값이 일치하는 인덱스 검색
matching_indices = []
for index, row in df2.iterrows():
    station_name = row['역명칭']
    pattern = r"\b{}\b".format(station_name.replace("(", r"\(").replace(")", r"\)"))
    regex = re.compile(pattern)
    if any(regex.search(station) for station in EV_Line_Gyeongui_Jungang_Df['역명칭']):
        matching_indices.append(index)

# 일치하는 인덱스에 대해 "엘리베이터" 컬럼에 1 표시
df2.loc[matching_indices, '엘리베이터'] = 1

matching_indices = []
for index, row in df2.iterrows():
    station_name = row['역명칭']
    pattern = r"\b{}\b".format(station_name.replace("(", r"\(").replace(")", r"\)"))
    regex = re.compile(pattern)
    if any(regex.search(station) for station in EV_Line_Gyeongchun_Df['역명칭']):
        matching_indices.append(index)

df2.loc[matching_indices, '엘리베이터'] = 1

matching_indices = []
for index, row in df2.iterrows():
    station_name = row['역명칭']
    pattern = r"\b{}\b".format(station_name.replace("(", r"\(").replace(")", r"\)"))
    regex = re.compile(pattern)
    if any(regex.search(station) for station in EV_Line_Suin_Bundang_Df['역명칭']):
        matching_indices.append(index)

df2.loc[matching_indices, '엘리베이터'] = 1

matching_indices = []
for index, row in df2.iterrows():
    station_name = row['역명칭']
    pattern = r"\b{}\b".format(station_name.replace("(", r"\(").replace(")", r"\)"))
    regex = re.compile(pattern)
    if any(regex.search(station) for station in EV_Line_New_Bundang_Df['역명칭']):
        matching_indices.append(index)

df2.loc[matching_indices, '엘리베이터'] = 1

matching_indices = []
for index, row in df2.iterrows():
    station_name = row['역명칭']
    pattern = r"\b{}\b".format(station_name.replace("(", r"\(").replace(")", r"\)"))
    regex = re.compile(pattern)
    if any(regex.search(station) for station in EV_Line_Ever_Df['역명칭']):
        matching_indices.append(index)

df2.loc[matching_indices, '엘리베이터'] = 1

matching_indices = []
for index, row in df2.iterrows():
    station_name = row['역명칭']
    pattern = r"\b{}\b".format(station_name.replace("(", r"\(").replace(")", r"\)"))
    regex = re.compile(pattern)
    if any(regex.search(station) for station in EV_Line_Uijeongbu_Rail_Df['역명칭']):
        matching_indices.append(index)

df2.loc[matching_indices, '엘리베이터'] = 1

matching_indices = []
for index, row in df2.iterrows():
    station_name = row['역명칭']
    pattern = r"\b{}\b".format(station_name.replace("(", r"\(").replace(")", r"\)"))
    regex = re.compile(pattern)
    if any(regex.search(station) for station in EV_Line_Incheon1_Df['역명칭']):
        matching_indices.append(index)

df2.loc[matching_indices, '엘리베이터'] = 1

matching_indices = []
for index, row in df2.iterrows():
    station_name = row['역명칭']
    pattern = r"\b{}\b".format(station_name.replace("(", r"\(").replace(")", r"\)"))
    regex = re.compile(pattern)
    if any(regex.search(station) for station in EV_Line_Incheon2_Df['역명칭']):
        matching_indices.append(index)

df2.loc[matching_indices, '엘리베이터'] = 1

        
# 결과 출력
df2.head(20)

       선명     역명칭   환승선명  환승이후역명 상하행  weight 엘리베이터 리프트 휠체어경사로 전화번호
0     9호선      삼전    9호선   종합운동장  하행       1
1     9호선    석촌고분    9호선      삼전  하행       1
2     9호선      석촌    9호선    석촌고분  하행       1     1
3     9호선    송파나루    9호선      석촌  하행       1
4     9호선    한성백제    9호선    송파나루  하행       1
5     9호선   올림픽공원    9호선    한성백제  하행       1     1
6     9호선  중앙보훈병원    9호선    둔촌오륜  하행       1
7   인천2호선     가재울  인천2호선    인천가좌  하행       1     1
8    우이신설      정릉   우이신설  북한산보국문  하행       1
9   인천2호선    시민공원  인천2호선      주안  하행       1     1
10  인천2호선   석바위시장  인천2호선    시민공원  하행       1     1
11  인천2호선    인천시청  인천2호선   석바위시장  하행       1     1
12  인천2호선   석천사거리  인천2호선    인천시청  하행       1     1
13  인천2호선   모래내시장  인천2호선   석천사거리  하행       1     1
14  인천2호선      만수  인천2호선   모래내시장  하행       1     1
15  인천2호선    남동구청  인천2호선      만수  하행       1     1
16  인천2호선   인천대공원  인천2호선    남동구청  하행       1     1
17     경춘     천마산     경춘    평내호평  하행       1     1
18     경춘      마석     경춘     천마산  하행       1     1
19     경춘     대성리     경춘      마석  하행       1     1

In [51]:
df2.tail(30)

        선명       역명칭   환승선명    환승이후역명 상하행  weight 엘리베이터 리프트 휠체어경사로 전화번호
729   수인분당        안산   수인분당      신길온천  상행       1     1
730   수인분당      신길온천   수인분당        정왕  상행       1     1
731   수인분당        정왕   수인분당       오이도  상행       1     1
732   수인분당       오이도   수인분당        달월  상행       1     1
733   수인분당        달월   수인분당        월곶  상행       1     1
734   수인분당        월곶   수인분당      소래포구  상행       1     1
735   수인분당      소래포구   수인분당      인천논현  상행       1     1
736   수인분당      인천논현   수인분당       호구포  상행       1     1
737   수인분당       호구포   수인분당   남동인더스파크  상행       1     1
738   수인분당   남동인더스파크   수인분당       원인재  상행       1     1
739   수인분당       원인재   수인분당        연수  상행       1     1
740   수인분당        연수   수인분당        송도  상행       1     1
741   수인분당        송도   수인분당       인하대  상행       1     1
742   수인분당       인하대   수인분당        숭의  상행       1     1
743   수인분당        숭의   수인분당        신포  상행       1     1
744    1호선        탕정    1호선        배방  상행       1     1
745   수인분당        신포   수인분당        인천  상행       1     1
746   수인분당        인천   수인분당        인천  상행       1     1
747    8호선        복정    8호선       남위례  상행       1     1
748    8호선       남위례    8호선        산성  상행       1     1
749    8호선        산성    8호선    남한산성입구  상행       1     1
750    8호선    남한산성입구    8호선     단대오거리  상행       1     1
751    8호선     단대오거리    8호선        신흥  상행       1     1
752    8호선        신흥    8호선        수진  상행       1     1
753    8호선        수진    8호선        모란  상행       1     1
754    8호선        모란    8호선        모란  상행       1     1
755    7호선        산곡    7호선        산곡  상행       1     1
756    7호선        석남    7호선        석남  상행       1     1
757  인천1호선  송도달빛축제공원  인천1호선  송도달빛축제공원  상행       1
758    6호선        신내    6호선        신내  상행       1     1

#### 이건 무시하세요.

In [ ]:
# df2.to_csv('환승경우의수+엘리베이터여부.csv', index=False,encoding='cp949')  # index=False로 설정하여 인덱스를 저장하지 않음

## 리프트 시작

In [52]:
Lift_Df =  pd.read_excel('/content/drive/MyDrive/Hackathon/Chuldong/(2차 전처리)울교통공사_휠체어리프트 설치현황_20230420.xlsx')
Lift_Df

     호선  역명칭    호기     승강기번호              설치위치   운행구간
0     1  서울역  내부#1  1902-362             C계단 측  B2-B1
1     1  신설동  외부#2  1903-467           6번 출구 측  1F-B1
2     1  신설동  내부#1  1903-415            제기동 방면  B2-B1
3     1  신설동  내부#2  1903-417            동묘앞 방면  B2-B1
4     1  신설동  내부#3  1903-416         연결통로(대합실)  B1-B1
..   ..  ...   ...       ...               ...    ...
106   8   잠실     2   1900790  석촌 방면1-1 환승통로 계단  B3-B2
107   8   잠실     3   1900791    사당 방면환승통로 끝 계단  통로-B2
108   8   복정     1   1900771           4번 출구 측  B1-F1
109   8   모란     1   3900941    환승통로(암사방면 6-4)  B3-B2
110   8   모란     2   3900942    환승통로(모란방면 1-1)  B3-B2

[111 rows x 6 columns]

In [53]:
Lift_Df = Lift_Df.drop_duplicates(subset='역명칭')
Lift_Df

     호선        역명칭    호기     승강기번호                      설치위치             운행구간
0     1        서울역  내부#1  1902-362                     C계단 측            B2-B1
1     1        신설동  외부#2  1903-467                   6번 출구 측            1F-B1
6     1        청량리  내부#2  1901-053                  회기 방면8-2            B2-B1
7     2        한양대  내부#1  1900-169                  뚝섬 방면8-2            1F-2F
8     2         용답  내부#2  1900-168                  신답 방면1-4            1F-2F
16    2         잠실  내부#1  1901-593             잠실쇼핑센터 측 연결계단            B1-B1
17    2         삼성  내부#1  1901-463                코액스 측 연결계단            B1-B1
18    2      신정네거리  내부#1  1902-885                 2,3번 출구 측            B2-B1
19    3      고속터미널  내부#1  1900-502                 환승통로(경부선)            B2-B1
20    3         교대  내부#1  1900-627           B1층 2,3호선 연결 계단            B1-B1
21    4         상계  내부#1  1901-032                 당고개 방면3-1            2F-3F
23    4         창동  내부#3  1902-457           연결통로(1호선, 2번출구)            F2-F3
27    4         사당  내부#1  1903-972          연결통로(2,4호선, 대합실)             B1-M
28    5        까치산     1   1901411                  화곡 방면1-2            B5-B4
30    5      영등포구청     3   1901375               영등포시장 방면2-3            B4-B2
31    5        서대문     1   1900038                5,6번 출구 사이            B1-F1
32    5       종로3가     1   1900031    광화문 방면1-1, 을지로4가 방면8-4            B5-B4
33    5        답십리     1   1900294                       대합실            B2-B1
34    5        장한평     1   1903443                       대합실            B2-B1
35    5        광나루     1   1901002                       대합실            B2-B1
36    5         강동     1  1900-817                       대합실            B4-B3
37    5        상일동     1   1901918         대합실(B1, 고덕 방면1-1)            B2-B1
40    5  동대문역사문화공원     1  1900-417           대합실(6,7번 출구 사이)            B3-B2
42    6         불광     1   1900413                      환승통로  B2(3호선)-B2(6호선)
44    6         구산     1   1900435                       대합실            B4-B1
45    6         새절     1   1900434                  증산 방면5-4            B2-B1
46    6   디지털미디어시티     1   1900229                  증산 방면8-4            B2-B1
49    6         합정     1  1903-890                       대합실  B1(6호선)-B1(2호선)
50    6        광흥창     1   1902001        상수 방면8-4, 대흥 방면1-1            B3-B2
51    6         대흥     2   1900447                   2번 출구 측            B1-1F
52    6         신당     1   1900251       청구 방면1-1, 동묘앞 방면8-4            B3-B2
57    6         월곡     1   1901031                아이센터 측(B2)            B2-B1
58    6        상월곡     1   1903486                  월곡 방면1-1            B3-B2
60    6         석계     1   1901003                 돌곶이 방면1-1            B3-B2
62    6        봉화산     1   1903412                 화랑대 방면8-4            B2-B1
64    6        동묘앞     1   1900043                       대합실            B2-B1
66    7        수락산     1   1902608                 도봉산 방면1-1            B3-B2
68    7         마들     1   1900923                 화장실 측(B2)            B2-B1
69    7       건대입구     3   1902289               뚝섬유원지 방면1-1            B1-2F
72    7         청담     1   1901913               뚝섬유원지 방면8-4            B4-B3
74    7         논현     1   1900831           대합실(1~10번출구 방면)            B2-B1
75    7         반포     1  1904-018            대합실(1~6번출구 방면)            B2-B1
80    7         이수     1   1901232              환승통로(당고개 방면)            B4-B2
83    7         대림     1   1901128  2호선 환승구간(E/S#10,11 옆 계단)            B1-F1
84    7        남구로     1   1901117               대림(7) 방면1-1            B5-B4
95    7    가산디지털단지     1   1901091                       대합실            B1-B1
99    7      광명사거리     1   3903261                  철산 방면8-4            B3-B2
100   7         온수     1   1901072         환승통로(7호선 승강장-1호선)            B2-B1
108   8         복정     1   1900771                   4번 출구 측            B1-F1
109   8         모란     1   3900941            환승통로(암사방면 6-4)            B3-B2

In [54]:
# "역명칭" 컬럼 값이 일치하는 인덱스 검색
matching_indices = []
for index, row in df2.iterrows():
    station_name = row['역명칭']
    pattern = r"\b{}\b".format(station_name.replace("(", r"\(").replace(")", r"\)"))
    regex = re.compile(pattern)
    if any(regex.search(station) for station in Lift_Df['역명칭']):
        matching_indices.append(index)

# 일치하는 인덱스에 대해 "엘리베이터" 컬럼에 1 표시
df2.loc[matching_indices, '리프트'] = 1

df2.head(50)

       선명       역명칭   환승선명    환승이후역명 상하행  weight 엘리베이터 리프트 휠체어경사로 전화번호
0     9호선        삼전    9호선     종합운동장  하행       1
1     9호선      석촌고분    9호선        삼전  하행       1
2     9호선        석촌    9호선      석촌고분  하행       1     1
3     9호선      송파나루    9호선        석촌  하행       1
4     9호선      한성백제    9호선      송파나루  하행       1
5     9호선     올림픽공원    9호선      한성백제  하행       1     1
6     9호선    중앙보훈병원    9호선      둔촌오륜  하행       1
7   인천2호선       가재울  인천2호선      인천가좌  하행       1     1
8    우이신설        정릉   우이신설    북한산보국문  하행       1
9   인천2호선      시민공원  인천2호선        주안  하행       1     1
10  인천2호선     석바위시장  인천2호선      시민공원  하행       1     1
11  인천2호선      인천시청  인천2호선     석바위시장  하행       1     1
12  인천2호선     석천사거리  인천2호선      인천시청  하행       1     1
13  인천2호선     모래내시장  인천2호선     석천사거리  하행       1     1
14  인천2호선        만수  인천2호선     모래내시장  하행       1     1
15  인천2호선      남동구청  인천2호선        만수  하행       1     1
16  인천2호선     인천대공원  인천2호선      남동구청  하행       1     1
17     경춘       천마산     경춘      평내호평  하행       1     1
18     경춘        마석     경춘       천마산  하행       1     1
19     경춘       대성리     경춘        마석  하행       1     1
20     경춘        청평     경춘       대성리  하행       1     1
21     경춘        상천     경춘        청평  하행       1     1
22     경춘        가평     경춘        상천  하행       1     1
23     경춘       굴봉산     경춘        가평  하행       1     1
24     경춘       백양리     경춘       굴봉산  하행       1     1
25     경춘        강촌     경춘       백양리  하행       1     1
26     경춘       김유정     경춘        강촌  하행       1     1
27     경춘       남춘천     경춘       김유정  하행       1     1
28     경춘        춘천     경춘       남춘천  하행       1     1
29  인천1호선        계양  인천1호선        계양  하행       1     1
30  인천1호선        귤현  인천1호선        계양  하행       1     1
31  인천1호선        박촌  인천1호선        귤현  하행       1     1
32  인천1호선        임학  인천1호선        박촌  하행       1     1
33  인천1호선        계산  인천1호선        임학  하행       1     1
34    3호선        원흥    3호선        원당  하행       1     1
35     경의        강매     경의        행신  하행       1     1
36   공항철도        서울   공항철도        서울  하행       1
37   공항철도        공덕   공항철도        서울  하행       1     1
38   공항철도      홍대입구   공항철도        공덕  하행       1     1
39   공항철도  디지털미디어시티   공항철도      홍대입구  하행       1     1   1
40   공항철도      김포공항   공항철도      마곡나루  하행       1     1
41   공항철도        계양   공항철도      김포공항  하행       1     1
42   공항철도        검암   공항철도        계양  하행       1     1
43   공항철도    청라국제도시   공항철도        검암  하행       1
44   공항철도    공항화물청사   공항철도        운서  하행       1
45   공항철도  인천공항1터미널   공항철도    공항화물청사  하행       1
46   공항철도  인천공항2터미널   공항철도  인천공항1터미널  하행       1
47   수인분당       오이도   수인분당       오이도  하행       1     1
48   수인분당        달월   수인분당       오이도  하행       1     1
49   수인분당        월곶   수인분당        달월  하행       1     1

## 리프트 완료

## 휠체어 경사로 시작

In [55]:
Wheelchair_Ramp =  pd.read_excel('/content/drive/MyDrive/Hackathon/Chuldong/(전처리)1-8호선 휠체어경사로 설치 현황_20220531.xlsx')
Wheelchair_Ramp = Wheelchair_Ramp.drop_duplicates(subset='역명칭')
Wheelchair_Ramp

     호선     역명칭     구분   위치
0     1      서울  외부출입구   #4
4     1      시청  외부출입구   #6
6     1      종각  외부E/V   #3
8     1    종로3가  외부출입구  #15
12    1    종로5가  외부E/V   #8
..   ..     ...    ...  ...
498   8      복정  외부출입구   #4
499   8      산성  외부E/V   #3
500   8  남한산성입구  외부출입구   #4
502   8   단대오거리  외부출입구   #1
503   8      모란  외부출입구  #12

[227 rows x 4 columns]

In [56]:
# "역명칭" 컬럼 값이 일치하는 인덱스 검색
matching_indices = []
for index, row in df2.iterrows():
    station_name = row['역명칭']
    pattern = r"\b{}\b".format(station_name.replace("(", r"\(").replace(")", r"\)"))
    regex = re.compile(pattern)
    if any(regex.search(station) for station in Wheelchair_Ramp['역명칭']):
        matching_indices.append(index)

# 일치하는 인덱스에 대해 "엘리베이터" 컬럼에 1 표시
df2.loc[matching_indices, '휠체어경사로'] = 1

# df2.head(50)
df2[df2['역명칭']=='가산디지털단지']

      선명      역명칭 환승선명 환승이후역명 상하행  weight 엘리베이터 리프트 휠체어경사로 전화번호
286  7호선  가산디지털단지  7호선    남구로  하행       1     1   1      1
473  1호선  가산디지털단지  1호선     구로  하행       1     1   1      1
286  7호선  가산디지털단지  7호선     철산  상행       1     1   1      1
473  1호선  가산디지털단지  1호선     독산  상행       1     1   1      1

## 전화번호 시작

In [57]:
Tel =  pd.read_csv('/content/drive/MyDrive/Hackathon/Chuldong/서울시 장애인 지하철 편의시설 정보(컬럼제거).csv', encoding='cp949')
Tel

,고유번호,노선,노선명칭,역명칭,운행방향1,운행방향2,엘리베이터 자막,사용여부,출구정보,전화번호
0,173,4,4호선,노원,당고개,오이도,승강기 위치는 9번 출구쪽에 있습니다 승강기를 이용하여 2층 대합실로 올라...,Y,"||1@상계6.7동 주민센터, 상계7동 치안센터, 상계중학교, 상계 119안전센터,...",긴급전화(역무실) : 02-6110-4111
1,245,5,5호선,청구,방화,"상일도,마천",NaN,Y,"||1@신당우체국, 한일은행, 장충초등교, 신흥항공, 국민은행, 문화시장 ||,||...",긴급전화(역무실) : 02-6311-5371
2,265,5,5호선,오금,방화,"상일도,마천",NaN,Y,"||1@송파우체국, 오금중학교, 오금동현대아파트 ||,||2@오금공원, 가락현대아파...",긴급전화(역무실) : 02-6311-5571
3,59,1,1호선,종로5가,소요산,인천,승강기 위치는 8번출구 뒤쪽에 있습니다. 승강기를 이용하여 지하1층 대합실...,Y,"||1@종로4가방면, 서울혜화경찰서, 종로5가 우체국, 중앙선거관리위원회 선거연수원...",긴급전화(역무실) : 02-6110-1291
4,64,1,1호선,청량리,소요산,인천,승강기 위치는 6번출구 쪽에 있습니다. 승강기를 이용하여 지하1층 대합실로...,Y,"||1@제기동방면, 경동,동서시장||,||2@홍릉(영휘원)방면, 서울청량리우체국, ...",긴급전화(역무실) : 02-6110-1241
...,...,...,...,...,...,...,...,...,...,...
452,13,1,1호선,병점,구로,천안,NaN,Y,NaN,긴급전화(역무실) : 031-234-7788
453,44,1,1호선,오류동,소요산,인천,NaN,Y,"||1@오류1동지역||,||2@오류2동지역||",긴급전화(역무실) : 02-2685-7788
454,138,3,3호선,원당,대화,수서,NaN,Y,"||1@원당농협성래지소||,||2@원당농협성래지소||,||3@약수터||,||4@고양...",긴급전화(역무실) : 031-965-8747
455,453,13,9호선,신반포,개화,신논현,NaN,Y,"||1@반포2동 주민센터, 반포우체국||,||2@신반포 중학교, 계성 초등학교||,...",긴급전화(역무실) : 02-2656-0922
456,188,4,4호선,서울역,당고개,오이도,승강기 위치는 12번 출구쪽에 있습니다. 승강기를 이용하여 지하 1층 대합...,Y,"||1@벽산125빌딩,LG역전빌딩,남대문경찰서||,||2@대일학원,경일학원,한일은행...",긴급전화(역무실) : 02-6110-4261

In [58]:
Tel['전화번호'] = Tel['전화번호'].str.replace('긴급전화(역무실) : ', '', regex=False)
#Tel['전화번호']
Tel

,고유번호,노선,노선명칭,역명칭,운행방향1,운행방향2,엘리베이터 자막,사용여부,출구정보,전화번호
0,173,4,4호선,노원,당고개,오이도,승강기 위치는 9번 출구쪽에 있습니다 승강기를 이용하여 2층 대합실로 올라...,Y,"||1@상계6.7동 주민센터, 상계7동 치안센터, 상계중학교, 상계 119안전센터,...",02-6110-4111
1,245,5,5호선,청구,방화,"상일도,마천",NaN,Y,"||1@신당우체국, 한일은행, 장충초등교, 신흥항공, 국민은행, 문화시장 ||,||...",02-6311-5371
2,265,5,5호선,오금,방화,"상일도,마천",NaN,Y,"||1@송파우체국, 오금중학교, 오금동현대아파트 ||,||2@오금공원, 가락현대아파...",02-6311-5571
3,59,1,1호선,종로5가,소요산,인천,승강기 위치는 8번출구 뒤쪽에 있습니다. 승강기를 이용하여 지하1층 대합실...,Y,"||1@종로4가방면, 서울혜화경찰서, 종로5가 우체국, 중앙선거관리위원회 선거연수원...",02-6110-1291
4,64,1,1호선,청량리,소요산,인천,승강기 위치는 6번출구 쪽에 있습니다. 승강기를 이용하여 지하1층 대합실로...,Y,"||1@제기동방면, 경동,동서시장||,||2@홍릉(영휘원)방면, 서울청량리우체국, ...",02-6110-1241
...,...,...,...,...,...,...,...,...,...,...
452,13,1,1호선,병점,구로,천안,NaN,Y,NaN,031-234-7788
453,44,1,1호선,오류동,소요산,인천,NaN,Y,"||1@오류1동지역||,||2@오류2동지역||",02-2685-7788
454,138,3,3호선,원당,대화,수서,NaN,Y,"||1@원당농협성래지소||,||2@원당농협성래지소||,||3@약수터||,||4@고양...",031-965-8747
455,453,13,9호선,신반포,개화,신논현,NaN,Y,"||1@반포2동 주민센터, 반포우체국||,||2@신반포 중학교, 계성 초등학교||,...",02-2656-0922
456,188,4,4호선,서울역,당고개,오이도,승강기 위치는 12번 출구쪽에 있습니다. 승강기를 이용하여 지하 1층 대합...,Y,"||1@벽산125빌딩,LG역전빌딩,남대문경찰서||,||2@대일학원,경일학원,한일은행...",02-6110-4261

In [59]:
Tel[Tel['역명칭']=='사당']

,고유번호,노선,노선명칭,역명칭,운행방향1,운행방향2,엘리베이터 자막,사용여부,출구정보,전화번호
235,195,4,4호선,사당,당고개,오이도,승강기 위치는 1번 출구쪽에 있습니다. 승강기를 이용하여 지하 1층 대합실...,Y,"||1@방배경찰서,이수초등교,방배2파출소||,||2@무지개아파트,지하철공사,동덕여중...",02-6110-4331
367,116,2,2호선,사당,시청,시청,승강기 위치는 14번출구 쪽에 있습니다. 승강기를 이용하여 지하 1층 대합...,Y,"||1@예술의전당 방면, 한전사당변전소, 사당공영주차장, 방배종합사회복지관, 서울까...",02-6110-2261

In [60]:
df2.head()

    선명   역명칭 환승선명 환승이후역명 상하행  weight 엘리베이터 리프트 휠체어경사로 전화번호
0  9호선    삼전  9호선  종합운동장  하행       1
1  9호선  석촌고분  9호선     삼전  하행       1
2  9호선    석촌  9호선   석촌고분  하행       1     1          1
3  9호선  송파나루  9호선     석촌  하행       1
4  9호선  한성백제  9호선   송파나루  하행       1